name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: |
          yarn install
      - name: Production Build
        run: |
          yarn build

  deploy: #https://github.com/marketplace/actions/react-deploy-to-s3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: jeanlescure/react-deploy-to-s3-action@main
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          NODE_ENV: development # optional: defaults to production
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1 # optional: defaults to us-east-1
          SOURCE_DIR: bundle # optional: defaults to public
